server:
  port: 8089
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: config-single-client
  cloud:
    config:
      uri: http://localhost:8088/
      profile: dev
      label: master
  rabbitmq:
    host: 47.106.131.191
    port: 5672
    username: admin
    password: 123456

security:
  basic:
    enabled: false

custom:
  username: fdfafdafdsafdasg1guest-new
  passwd: 23guest-new
